title: Mathews Alves # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, I'm Mathews Alves a passionate game developer, who loves to design and develop games applications. I am currently doing a Masters in Digital Game Development at the Aveiro's University in Portugal.  
  <br><br>
  Email: <a href=mailto:“mathewsalves1@outlook.com”>mathewsalves1@outlook.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/mathews-alves/">View My LinkedIn Profile</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
